/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ac.uryukyu.ie.e225737;

import org.junit.jupiter.api.Test;

import com.google.common.annotations.VisibleForTesting;
import com.google.j2objc.annotations.ReflectionSupport.Level;
import static org.junit.jupiter.api.Assertions.*;

class Level1Test{
    @Test
        Level testCul = new Level1();
        testCul.Sinkou();
        if(myAnswer == answer){
            assertEquals()
        }
}

